version: '3'

volumes:
  db-data:

networks:
  app:

services:
  database:
    image: postgres:12.5-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./postgres/:/docker-entrypoint-initdb.d/

  pgAdmin:
    image: dpage/pgadmin4:4.29
    container_name: pgAdmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "3000:80"
    networks:
      - app
    depends_on: 
      - database

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5000:5000"
      - "5003:5003"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    depends_on:
      - store-service

  store-service:
    image: php:7-fpm
    container_name: store-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./store-service/:/var/www/app/
    networks:
      - app
    depends_on:
      - database

  warranty-service:
    image: kariae/symfony-php:7.4
    container_name: warranty-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./warranty-service/:/var/www/app/
    networks:
      - app
    depends_on:
      - database